# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/camiloocampo/Documents/Max\ 8/Packages/min-devkit/source/min-api/max-api/script/max-posttarget.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/camiloocampo/Documents/Max\ 8/Packages/min-devkit/source/min-api/max-api/script/max-pretarget.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/camiloocampo/Documents/Max\ 8/Packages/min-devkit/source/min-api/script/min-posttarget.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/camiloocampo/Documents/Max\ 8/Packages/min-devkit/source/min-api/script/min-pretarget.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/camiloocampo/Documents/Max\ 8/Packages/min-devkit/source/min-api/test/min-object-unittest.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/camiloocampo/Documents/Max\ 8/Packages/min-devkit/source/projects/min.euclidean_tilde/CMakeLists.txt))

/Users/camiloocampo/Documents/Max\ 8/Packages/min-devkit/build/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.17.1/bin/cmake -H/Users/camiloocampo/Documents/Max\ 8/Packages/min-devkit -B/Users/camiloocampo/Documents/Max\ 8/Packages/min-devkit/build
